# Generated by Django 5.1.5 on 2025-02-03 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(verbose_name='Date Round Starts')),
                ('end_date', models.DateTimeField(verbose_name='Date Round Ends')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('eliminated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('round_eliminated', models.BooleanField(default=False)),
                ('eliminated_permanently', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_round', to='assignments.round')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team_1', to='assignments.team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team_2', to='assignments.team')),
                ('winning_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_wining_team', to='assignments.team')),
            ],
        ),
    ]
