# Generated by Django 5.1.5 on 2025-02-03 15:07

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='viewing_code',
            field=models.CharField(default=assignments.models.Team.generate_viewing_code, max_length=8),
        ),
    ]
