# Generated by Django 4.2.18 on 2025-02-03 17:36

import assignments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_team_viewing_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='viewing_code',
            field=models.CharField(default=assignments.models.Team.generate_viewing_code, max_length=8, unique=True),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.AddField(
            model_name='target',
            name='prosecuting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosecuting_team', to='assignments.team'),
        ),
        migrations.AddField(
            model_name='target',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_round', to='assignments.round'),
        ),
        migrations.AddField(
            model_name='target',
            name='target_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_team', to='assignments.team'),
        ),
        migrations.AddField(
            model_name='target',
            name='winning_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_wining_team', to='assignments.team'),
        ),
    ]
