# Generated by Django 4.2.18 on 2025-02-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_target_alter_team_viewing_code_delete_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='winning_team',
        ),
        migrations.AddField(
            model_name='target',
            name='eliminations',
            field=models.IntegerField(default=0),
        ),
    ]
