# Generated by Django 4.2.18 on 2025-02-14 22:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2025, 2, 14, 22, 59, 17, 746625, tzinfo=datetime.timezone.utc))),
                ('elimed_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elimed_participant', to='assignments.participant')),
                ('eliminator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminator', to='assignments.participant')),
                ('target_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='assignments.target')),
            ],
        ),
    ]
