# Generated by Django 4.2.18 on 2025-02-15 13:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_remove_kill_date_remove_kill_elimed_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kill',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 15, 13, 50, 44, 143072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='kill',
            name='elimed_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elimed_participant', to='assignments.participant'),
        ),
        migrations.AddField(
            model_name='kill',
            name='eliminator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminator', to='assignments.participant'),
        ),
        migrations.AddField(
            model_name='kill',
            name='target_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='assignments.target'),
        ),
    ]
