# Generated by Django 4.2.18 on 2025-02-15 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_kill_date_kill_elimed_participant_kill_eliminator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kill',
            old_name='target_team',
            new_name='target',
        ),
        migrations.AlterField(
            model_name='kill',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 15, 14, 2, 59, 959578, tzinfo=datetime.timezone.utc)),
        ),
    ]
