# Generated by Django 4.2.18 on 2025-02-15 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_rename_target_team_kill_target_alter_kill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kill',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 15, 14, 44, 27, 968158, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='kill',
            name='elimed_participant',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='target', chained_model_field='prosecuting_team.participants', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elimed_participant', to='assignments.participant'),
        ),
    ]
