# Generated by Django 4.2.18 on 2025-02-17 16:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_alter_kill_date_alter_kill_elimed_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kill',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='kill',
            name='elimed_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elimed_participant', to='assignments.participant'),
        ),
    ]
