# Generated by Django 4.2.18 on 2025-02-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_alter_kill_date_alter_kill_elimed_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='eliminated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kill',
            name='elimed_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminations', to='assignments.participant'),
        ),
        migrations.AlterField(
            model_name='kill',
            name='eliminator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='assignments.participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='assignments.team'),
        ),
        migrations.AlterField(
            model_name='target',
            name='prosecuting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosecuting_targets', to='assignments.team'),
        ),
        migrations.AlterField(
            model_name='target',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='assignments.round'),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='assignments.team'),
        ),
    ]
