# Generated by Django 4.2.18 on 2025-03-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_round_completed_team_eliminated_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('rules_suspended', models.CharField(max_length=600)),
                ('notification_time', models.DateTimeField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
        ),
    ]
