# Generated by Django 4.2.18 on 2025-03-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_issue_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesuspension',
            name='rules_suspended',
            field=models.TextField(),
        ),
    ]
