# Generated by Django 4.2.18 on 2025-03-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_alter_rulesuspension_rules_suspended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesuspension',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rulesuspension',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
