# Generated by Django 4.2.18 on 2025-03-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0017_alter_vote_issue_alter_vote_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
