# Generated by Django 4.2.18 on 2025-03-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0020_kill_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kill',
            name='video_link',
        ),
    ]
