# Generated by Django 4.2.18 on 2025-03-31 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0022_kill_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kill',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='assignments.target'),
        ),
    ]
