# Generated by Django 4.2.18 on 2025-04-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0023_alter_kill_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='min_progression_kill_count',
            field=models.IntegerField(default=0),
        ),
    ]
