# Generated by Django 4.2.18 on 2025-04-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0025_progressionoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='min_revive_kill_count',
            field=models.IntegerField(default=2),
        ),
    ]
